type Template = {
  competencies: string
  capacities: string
  performance: string
  purpose: string
  evidence: string
  transversalApproaches: string
  seqInicio: string
  seqDesarrollo: string
  seqDurante: string
  seqDespues: string
  seqCierre: string
  gestionAprendizaje: string
  evaluationTechniques: string
  evaluationInstruments: string
  resources: string
  reflections: string
}

const comunes = {
  enfoques: "Enfoque de derechos: Los estudiantes ejercen y exigen sus derechos y responsabilidades.\nEnfoque inclusivo: Valoramos y respetamos las diferencias individuales.\nEnfoque intercultural: Reconocemos y dialogamos entre diversas culturas.\nEnfoque de igualdad de género: Promovemos oportunidades equitativas.\nEnfoque ambiental: Cuidamos y protegemos nuestro entorno.\nEnfoque de orientación al bien común: Actuamos con solidaridad y responsabilidad.",
  reflex: "La sesión se desarrolló según lo planificado, logrando que los estudiantes participen activamente y alcancen el propósito de aprendizaje. Se evidenció interés y compromiso durante las actividades. Se sugiere continuar reforzando los aprendizajes con actividades de extensión en casa. Para futuras sesiones, considerar la diversificación de estrategias según los ritmos y estilos de aprendizaje de los estudiantes. Es importante seguir fortaleciendo el trabajo colaborativo y la autonomía.",
  gestion: "Define metas de aprendizaje personales orientadas al propósito de la sesión.\nOrganiza acciones estratégicas para alcanzar dichas metas.\nMonitorea su propio desempeño durante el desarrollo de las actividades.\nAjusta y regula sus estrategias según las dificultades que enfrenta.\nEvalúa sus avances y reflexiona sobre cómo mejorar continuamente.",
  seqDuranteDefault: "• LECTURA GUIADA: El docente modela la lectura con entonación y pausas adecuadas.\n• ESTRATEGIAS DE LECTURA: Aplicación de subrayado, sumillado e identificación de palabras clave.\n• COMPRENSIÓN LECTORA: Los estudiantes responden preguntas literales, inferenciales y críticas.\n• TRABAJO COLABORATIVO: Análisis y discusión del texto en pares o equipos.\n• REGISTRO DE APRENDIZAJE: Elaboración de organizadores gráficos (mapa conceptual, cuadro sinóptico, línea de tiempo).",
  seqDespuesDefault: "• SOCIALIZACIÓN: Puesta en común de las ideas principales del texto.\n• PRODUCCIÓN ESCRITA: Los estudiantes producen un texto breve relacionado con lo leído.\n• REVISIÓN ENTRE PARES: Coevaluación de las producciones usando una lista de cotejo.\n• MEJORA Y REESCRITURA: Incorporación de sugerencias para mejorar los textos.\n• COMPARTIR PRODUCCIONES: Lectura voluntaria de los textos mejorados ante el grupo.",
}

const porNivel: Record<string, Record<string, Partial<Template>>> = {
  inicial: {
    default: {
      competencies: "Convive y participa democráticamente en la búsqueda del bien común.\nSe comunica oralmente en su lengua materna.\nConstruye su identidad.\nIndaga mediante métodos científicos para construir sus conocimientos.\nCrea proyectos desde los lenguajes artísticos.",
      capacities: "Obtiene información del texto oral.\nInfiere e interpreta información del texto oral.\nReflexiona y evalúa la forma, el contenido y contexto del texto oral.\nComprende las relaciones entre los objetos del entorno.\nExplora y experimenta con materiales diversos.\nExpresa sus emociones y preferencias.",
      performance: "Participa en conversaciones espontáneas respetando turnos.\nExpresa sus emociones, ideas y experiencias con gestos y palabras.\nExplora libremente materiales del entorno y describe sus características.\nSe relaciona con sus compañeros de manera respetuosa.\nResponde preguntas simples sobre lo que observa y escucha.\nRepresenta gráficamente sus experiencias y vivencias.",
      purpose: "Que los niños y niñas exploren, descubran y aprendan de manera activa y lúdica, desarrollando habilidades sociales, comunicativas, cognitivas y motoras a través de experiencias significativas que promuevan su autonomía, creatividad y pensamiento crítico, en un ambiente seguro y afectivo donde se sientan valorados y motivados.",
      evidence: "Participación activa y espontánea durante las actividades lúdicas y pedagógicas.\nProducciones gráfico-plásticas (dibujos, modelados, collage).\nRespuestas verbales a preguntas de comprensión y reflexión.\nExpresión corporal y oral durante juegos y dramatizaciones.\nRegistro de observación del desarrollo de habilidades socioemocionales.",
      transversalApproaches: comunes.enfoques,
      seqInicio: "• ASAMBLEA: Docente y niños se sientan en círculo, cantan la canción de bienvenida y saludan a sus compañeros.\n• MOTIVACIÓN: Se presenta un objeto sorpresa, una imagen llamativa o un cuento breve relacionado con el tema.\n• SABERES PREVIOS: ¿Qué sabemos sobre…? ¿Han visto antes…? ¿Cómo es…? ¿Qué creen que pasará?\n• PROPÓSITO: La docente comunica de manera clara y sencilla: \"Hoy vamos a…\" usando un lenguaje adecuado a la edad.\n• ACUERDOS: Recordamos las normas de convivencia: escuchar, respetar turnos, cuidar los materiales.",
      seqDesarrollo: "• EXPLORACIÓN LIBRE: Los niños manipulan, observan y experimentan con los materiales preparados.\n• ACTIVIDAD GUIADA: La docente modela el procedimiento, realiza preguntas de andamiaje y acompaña el proceso.\n• JUEGO DE ROLES / EXPERIMENTACIÓN: Los niños representan situaciones, recrean escenas o realizan experimentos sencillos.\n• ACOMPAÑAMIENTO INDIVIDUALIZADO: La docente se acerca a cada niño, observa su proceso, formula preguntas y brinda retroalimentación oportuna.\n• VERBALIZACIÓN: ¿Qué estás haciendo? ¿Cómo lo hiciste? ¿Qué pasó? ¿Qué te gustó más?",
      seqDurante: comunes.seqDuranteDefault,
      seqDespues: comunes.seqDespuesDefault,
      seqCierre: "• PUESTA EN COMÚN: Los niños muestran y explican sus trabajos al grupo.\n• METACOGNICIÓN: ¿Qué aprendimos hoy? ¿Cómo lo aprendimos? ¿Qué fue lo más fácil? ¿Qué fue lo más difícil? ¿Para qué nos sirve?\n• CIERRE AFECTIVO: Canción de despedida, abrazo colectivo o mensaje positivo.\n• EXTENSIÓN: Sugerencia para realizar en casa con la familia.",
      gestionAprendizaje: comunes.gestion,
      evaluationTechniques: "Observación sistemática\nAnálisis de producciones y trabajos\nDiálogo y conversación\nJuego libre",
      evaluationInstruments: "Lista de cotejo con indicadores\nFicha de observación del desarrollo\nPortafolio de evidencias\nRegistro anecdótico\nEscala de actitudes",
      resources: "Material concreto diverso (bloques lógicos, plastilina, crayones, temperas, papeles de colores)\nLáminas ilustrativas y tarjetas de vocabulario\nCuentos y libros álbum\nEquipo de sonido y canciones infantiles\nFichas de trabajo y hojas de aplicación\nMaterial reciclable y de la comunidad\nTíteres y disfraces\nEspacio al aire libre (patio, jardín)",
      reflections: comunes.reflex,
    },
  },
  primaria: {
    default: {
      competencies: "Resuelve problemas de cantidad.\nResuelve problemas de regularidad, equivalencia y cambio.\nResuelve problemas de forma, movimiento y localización.\nResuelve problemas de gestión de datos e incertidumbre.\nSe comunica oralmente en su lengua materna.\nLee diversos tipos de textos escritos.\nEscribe diversos tipos de textos.\nConvive y participa democráticamente.\nIndaga mediante métodos científicos.",
      capacities: "Traduce cantidades a expresiones numéricas.\nComunica su comprensión sobre los números y las operaciones.\nUsa estrategias y procedimientos de estimación y cálculo.\nArgumenta afirmaciones sobre las relaciones numéricas y las operaciones.\nObtiene información del texto oral y escrito.\nInfiere e interpreta información del texto.\nReflexiona y evalúa la forma, contenido y contexto.\nAdecúa, organiza y desarrolla las ideas de forma coherente.\nProblematiza situaciones para hacer indagación.\nDiseña estrategias para hacer indagación.",
      performance: "Establece relaciones entre datos y acciones de agregar, quitar, comparar e igualar cantidades.\nExpresa con material concreto, gráfico o simbólico su comprensión de la decena y centena.\nEmplea estrategias heurísticas y procedimientos de cálculo mental y escrito para resolver problemas.\nExplica con sus propias palabras cómo resolvió el problema y por qué su estrategia funcionó.\nIdentifica información explícita en textos de estructura simple.\nDeduce características implícitas de personajes, animales, objetos o lugares.\nOpina sobre el contenido y la organización del texto.\nEscribe textos breves con coherencia, cohesión y adecuación al propósito.",
      purpose: "Que los estudiantes desarrollen competencias comunicativas, matemáticas, científicas y ciudadanas mediante situaciones significativas que les permitan analizar, reflexionar y resolver problemas de su contexto, fortaleciendo su pensamiento crítico, creativo y colaborativo, con énfasis en la autonomía y la metacognición como herramientas para el aprendizaje permanente.",
      evidence: "Resolución de problemas y ejercicios en fichas de práctica y cuaderno de trabajo.\nProducción de textos escritos (narrativos, descriptivos, instructivos) con coherencia y creatividad.\nComprensión lectora demostrada en organizadores gráficos y respuestas a preguntas literales, inferenciales y críticas.\nParticipación argumentada en diálogos, debates y exposiciones orales.\nExperimentación y registro de observaciones en cuaderno de campo.\nTrabajos colaborativos y coevaluación entre pares.",
      transversalApproaches: comunes.enfoques,
      seqInicio: "• SALUDO Y MOTIVACIÓN: Dinámica de activación (juego, acertijo, imagen provocadora, video corto, pregunta retadora).\n• RECOJO DE SABERES PREVIOS: ¿Qué sabemos sobre…? ¿Dónde lo hemos visto? ¿Qué experiencias tenemos?\n• CONFLICTO COGNITIVO: Situación problemática que desafíe las ideas previas y genere curiosidad.\n• PROPÓSITO DE LA SESIÓN: Presentación clara del objetivo: \"Hoy aprenderemos a…\"\n• ORGANIZACIÓN: Acuerdos de trabajo, conformación de equipos, distribución de materiales.",
      seqDesarrollo: "• PRESENTACIÓN DEL CONTENIDO: El docente presenta y explica la nueva información utilizando diversos recursos (esquemas, ejemplos, modelado).\n• TRABAJO COLABORATIVO: Los estudiantes resuelven situaciones problemáticas en equipos heterogéneos, aplicando estrategias y compartiendo ideas.\n• ACOMPAÑAMIENTO Y RETROALIMENTACIÓN: El docente monitorea el trabajo, formula preguntas de andamiaje y brinda retroalimentación formativa.\n• PRÁCTICA INDEPENDIENTE: Actividad individual donde el estudiante aplica lo aprendido para consolidar y transferir.\n• SOCIALIZACIÓN: Puesta en común de resultados, estrategias y conclusiones. Contraste de procedimientos.",
      seqDurante: comunes.seqDuranteDefault,
      seqDespues: comunes.seqDespuesDefault,
      seqCierre: "• METACOGNICIÓN GUIADA: ¿Qué aprendí? ¿Cómo lo aprendí? ¿Qué estrategias me funcionaron? ¿Qué dificultades tuve y cómo las superé?\n• EVALUACIÓN DE LA SESIÓN: Autoevaluación del estudiante y coevaluación del trabajo en equipo.\n• REFLEXIÓN DOCENTE: ¿Qué funcionó bien? ¿Qué mejorar? ¿Todos los estudiantes lograron el propósito?\n• TAREA O RETO: Actividad de extensión para aplicar lo aprendido en el contexto familiar o comunitario.",
      gestionAprendizaje: comunes.gestion,
      evaluationTechniques: "Observación sistemática\nAnálisis de producciones y trabajos\nPruebas escritas y orales\nPrácticas dirigidas\nRúbricas de evaluación\nAutoevaluación y coevaluación",
      evaluationInstruments: "Lista de cotejo\nRúbrica analítica\nFicha de observación\nPrueba escrita\nPortafolio de evidencias\nEscala de valoración\nGuía de autoevaluación",
      resources: "Pizarra acrílica y plumones de colores\nFichas de trabajo y hojas de aplicación\nTextos escolares del MINEDU y otros materiales educativos\nMaterial concreto (base 10, regletas de Cuisenaire, tangram, geoplanos, ábacos)\nProyector multimedia y laptop\nBiblioteca del aula\nCuaderno de trabajo y fichas de lectura\nMaterial reciclable y manipulativo\nPlataforma educativa virtual (si aplica)",
      reflections: comunes.reflex,
    },
    "Comunicación": {
      competencies: "Se comunica oralmente en su lengua materna.\nLee diversos tipos de textos escritos en su lengua materna.\nEscribe diversos tipos de textos en su lengua materna.",
      capacities: "Obtiene información del texto oral y escrito.\nInfiere e interpreta información del texto.\nReflexiona y evalúa la forma, el contenido y contexto del texto.\nAdecúa, organiza y desarrolla las ideas de forma coherente y cohesionada.\nUtiliza convenciones del lenguaje escrito de forma pertinente.\nReflexiona y evalúa la forma, el contenido y contexto de su texto escrito.",
      performance: "Identifica información explícita que se encuentra en lugares evidentes del texto (inicio, final) en textos narrativos y descriptivos simples.\nDeduce características implícitas de personajes, seres, objetos, lugares y hechos.\nExplica el tema y el propósito comunicativo del texto.\nOpina sobre hechos e ideas del texto, dando razones sencillas.\nEscribe textos narrativos y descriptivos coherentes con imágenes y lenguaje apropiado.\nRevisa y mejora sus textos con ayuda del docente y pares.",
      purpose: "Que los estudiantes desarrollen su competencia comunicativa a través de la lectura, análisis y producción de diversos tipos de textos, fortaleciendo su capacidad de comprensión literal, inferencial y crítica, así como su expresión oral y escrita con creatividad, coherencia y adecuación a la situación comunicativa.",
      evidence: "Producción de textos escritos (cuento, poesía, noticia, afiche) con estructura y propósito definido.\nOrganizadores gráficos que evidencien la comprensión del texto leído (mapa conceptual, cuadro sinóptico, línea de tiempo).\nParticipación en diálogos y exposiciones orales con claridad y argumentación.\nRespuestas a preguntas de comprensión en sus diferentes niveles.\nPortafolio de producciones escritas con correcciones y mejoras.",
      seqInicio: "• MOTIVACIÓN: Lectura compartida de un texto breve, imagen llamativa o video relacionado con el tema.\n• SABERES PREVIOS: ¿Qué sabemos sobre este tipo de texto? ¿Qué textos hemos leído antes? ¿Para qué sirven?\n• PROPÓSITO: \"Hoy leeremos y analizaremos un/una [tipo de texto] para comprender su mensaje y aprender a producir el nuestro.\"\n• ACUERDOS: Normas para la lectura y el trabajo colaborativo.",
      seqDesarrollo: "• ACTIVACIÓN DE CONOCIMIENTOS PREVIOS: Predicción a partir del título, imágenes y silueta del texto.\n• PROPÓSITO DE LECTURA: Definición del propósito: leer para disfrutar, para informarse, para aprender.\n• FORMULACIÓN DE HIPÓTESIS: Los estudiantes anticipan el contenido del texto.\n• VOCABULARIO PREVIO: Identificación y explicación de palabras clave o desconocidas.",
      seqDurante: "• LECTURA MODELADA: El docente lee en voz alta con entonación, pausas y expresividad adecuadas.\n• LECTURA COMPARTIDA: Los estudiantes leen en pares o en cadena, alternando párrafos.\n• ESTRATEGIAS DE LECTURA: Aplicación de subrayado de ideas principales, sumillado y anotaciones al margen.\n• COMPRENSIÓN LITERAL: Identificación de personajes, hechos, lugares y tiempos. Preguntas: ¿Qué? ¿Quién? ¿Dónde? ¿Cuándo?\n• COMPRENSIÓN INFERENCIAL: Deducción de características implícitas, causas y consecuencias. Preguntas: ¿Cómo? ¿Por qué? ¿Qué significa?\n• COMPRENSIÓN CRÍTICA: Opinión y juicio sobre el contenido. Preguntas: ¿Qué opinas? ¿Cambiarías algo? ¿Qué harías tú?",
      seqDespues: "• ORGANIZADOR GRÁFICO: Elaboración de mapa conceptual, cuadro sinóptico o línea de tiempo sobre el texto leído.\n• PRODUCCIÓN ESCRITA: Planificación, textualización y revisión de un texto propio inspirado en lo leído.\n• SOCIALIZACIÓN: Lectura voluntaria de las producciones ante el grupo.\n• RETROALIMENTACIÓN ENTRE PARES: Coevaluación usando lista de cotejo, formulación de sugerencias de mejora.\n• REESCRITURA: Incorporación de sugerencias para mejorar el texto producido.",
      seqCierre: "• METACOGNICIÓN: ¿Qué estrategias usé para comprender el texto? ¿Cómo organicé mis ideas para escribir? ¿Qué aprendí sobre este tipo de texto?\n• REFLEXIÓN: ¿Para qué me sirve lo aprendido? ¿En qué situaciones puedo aplicarlo?\n• EXTENSIÓN: Leer o escribir en casa un texto similar y compartirlo en la próxima clase.",
      gestionAprendizaje: "Define metas de aprendizaje para comprender y producir textos.\nOrganiza acciones estratégicas: lectura atenta, subrayado, consulta de diccionario.\nMonitorea su comprensión durante la lectura y ajusta estrategias si es necesario.\nEvalúa la calidad de sus producciones escritas y las mejora.\nReflexiona sobre su progreso en el desarrollo de competencias comunicativas.",
      resources: "Texto del MINEDU (Comunicación)\nFichas de lectura y comprensión lectora\nDiccionario físico y digital\nLáminas, tarjetas léxicas y pictogramas\nPapelotes, plumones y colores\nBiblioteca del aula (cuentos, poemas, fábulas, noticias)\nEquipo multimedia y parlantes\nOrganizadores gráficos impresos",
    },
    "Matemática": {
      competencies: "Resuelve problemas de cantidad.\nResuelve problemas de regularidad, equivalencia y cambio.\nResuelve problemas de forma, movimiento y localización.\nResuelve problemas de gestión de datos e incertidumbre.",
      capacities: "Traduce cantidades a expresiones numéricas.\nComunica su comprensión sobre los números y las operaciones.\nUsa estrategias y procedimientos de estimación y cálculo.\nArgumenta afirmaciones sobre las relaciones numéricas.\nTraduce datos y condiciones a expresiones algebraicas y gráficas.\nComunica su comprensión sobre las relaciones algebraicas.\nUsa estrategias y procedimientos para encontrar equivalencias y reglas generales.\nArgumenta afirmaciones sobre relaciones de cambio y equivalencia.",
      performance: "Establece relaciones entre datos y acciones de agregar, quitar, comparar, igualar, repetir o repartir cantidades.\nExpresa con material concreto, dibujos y simbología su comprensión del valor posicional de números hasta la centena.\nEmplea estrategias heurísticas y procedimientos de cálculo mental, escrito y con uso de calculadora.\nJustifica sus procesos de resolución y resultados mediante ejemplos concreto y gráficos.\nTraduce situaciones de la vida cotidiana a expresiones numéricas y modelos aditivos y multiplicativos.",
      purpose: "Que los estudiantes desarrollen el pensamiento matemático mediante la resolución de problemas significativos de su contexto, aplicando estrategias formales e informales, comunicando sus resultados con precisión y argumentando sus procesos, en un ambiente de colaboración y respeto por las diferentes formas de pensar.",
      evidence: "Resolución de problemas aritméticos y geométricos en fichas de trabajo y cuaderno.\nExplicación oral y escrita de las estrategias utilizadas para resolver problemas.\nElaboración de gráficos, tablas y esquemas para representar datos y relaciones.\nParticipación en dinámicas de resolución colaborativa y desafíos matemáticos.\nPortafolio con diversos problemas resueltos y reflexiones sobre el proceso.",
      seqInicio: "• MOTIVACIÓN: Situación problemática de la vida cotidiana o juego matemático (bingo numérico, carrera de operaciones, adivinanzas).\n• SABERES PREVIOS: ¿Qué operaciones conocemos? ¿Cómo resolvemos problemas similares? ¿Qué estrategias usamos?\n• CONFLICTO COGNITIVO: Presentación de un problema que no se puede resolver solo con los conocimientos previos.\n• PROPÓSITO: \"Hoy aprenderemos a… resolviendo problemas de…\"",
      seqDesarrollo: "• COMPRENSIÓN DEL PROBLEMA: Lectura colectiva, identificación de datos, pregunta y condiciones.\n• BÚSQUEDA DE ESTRATEGIAS: Trabajo en equipos. Los estudiantes proponen y discuten posibles estrategias de resolución.\n• REPRESENTACIÓN: Uso de material concreto, gráficos o esquemas para modelar el problema.\n• RESOLUCIÓN Y ACOMPAÑAMIENTO: Los estudiantes resuelven mientras el docente monitorea, formula preguntas y retroalimenta.\n• PLENARIA: Socialización de estrategias, resultados y conclusiones. Formalización del conocimiento matemático.",
      seqDurante: "• PRÁCTICA GUIADA: Los estudiantes resuelven ejercicios de aplicación en parejas con acompañamiento docente.\n• DIFERENCIACIÓN: Actividades graduadas por nivel de dificultad según el ritmo de aprendizaje.\n• REGISTRO: Los estudiantes anotan sus procedimientos y resultados en el cuaderno.\n• VERIFICACIÓN: Revisión colectiva de respuestas, identificación de errores comunes y corrección.",
      seqDespues: "• PLENARIA: Socialización de estrategias de resolución y resultados obtenidos.\n• FORMALIZACIÓN: Sistematización del conocimiento matemático (definiciones, propiedades, algoritmos).\n• TRANSFERENCIA: Aplicación de lo aprendido a nuevas situaciones problemáticas.\n• REFLEXIÓN: ¿Qué aprendí sobre la resolución de problemas? ¿Qué estrategias fueron más efectivas?",
      gestionAprendizaje: "Define metas de aprendizaje para resolver problemas matemáticos.\nOrganiza acciones estratégicas: analizar datos, elegir procedimientos, verificar resultados.\nMonitorea su progreso durante la resolución y ajusta estrategias.\nEvalúa la pertinencia de sus procedimientos y la exactitud de sus resultados.\nReflexiona sobre su desarrollo del pensamiento matemático.",
      resources: "Material concreto (base 10, regletas de Cuisenaire, ábacos, geoplanos, tangram, material multibase)\nPizarra y plumones\nFichas de trabajo graduadas por nivel de dificultad\nTextos escolares del MINEDU\nProyector multimedia\nJuegos matemáticos (dominós, barajas numéricas, bingos)\nCuaderno de trabajo",
    },
    "Ciencia y Tecnología": {
      competencies: "Indaga mediante métodos científicos para construir conocimientos.\nExplica el mundo físico basándose en conocimientos sobre los seres vivos, materia y energía, biodiversidad, Tierra y universo.\nDiseña y construye soluciones tecnológicas para resolver problemas de su entorno.",
      capacities: "Problematiza situaciones para hacer indagación.\nDiseña estrategias para hacer indagación.\nGenera y registra datos e información.\nAnaliza datos e información.\nEvalúa y comunica el proceso y resultados de su indagación.\nDetermina una alternativa de solución tecnológica.\nDiseña la alternativa de solución tecnológica.\nImplementa y valida la alternativa de solución tecnológica.\nEvalúa y comunica el funcionamiento y los impactos de su solución tecnológica.",
      performance: "Formula preguntas sobre fenómenos naturales observados en su entorno.\nPropone hipótesis basadas en sus observaciones y conocimientos previos.\nRealiza experimentos sencillos siguiendo un procedimiento establecido.\nRegistra datos y observaciones en tablas, dibujos o gráficos simples.\nComunica sus conclusiones y hallazgos de forma verbal y gráfica.\nPropone soluciones tecnológicas creativas a problemas cotidianos.",
      purpose: "Que los estudiantes desarrollen una cultura científica y tecnológica mediante la indagación, experimentación y diseño de soluciones, explorando fenómenos naturales y construyendo explicaciones basadas en evidencias, desarrollando pensamiento crítico, curiosidad científica y compromiso ambiental.",
      evidence: "Registro de observaciones y datos experimentales en cuaderno de campo o fichas.\nInforme científico grupal con hipótesis, procedimiento, resultados y conclusiones.\nPrototipo o maqueta de solución tecnológica.\nExposición oral del proceso de indagación y resultados.\nParticipación en ferias de ciencia o exposiciones escolares.",
      seqInicio: "• MOTIVACIÓN: Experimento demostrativo, video científico, pregunta provocadora o salida al entorno natural.\n• SABERES PREVIOS: ¿Qué sabemos sobre…? ¿Por qué ocurre…? ¿Cómo funciona…?\n• CONFLICTO COGNITIVO: Situación que contradice las ideas previas.\n• PROPÓSITO: \"Hoy seremos científicos y descubriremos… a través de la experimentación.\"",
      seqDesarrollo: "• PLANTEAMIENTO DEL PROBLEMA: Formulación de la pregunta de indagación.\n• FORMULACIÓN DE HIPÓTESIS: Los estudiantes proponen respuestas tentativas.\n• DISEÑO EXPERIMENTAL: Planificación de los pasos, materiales y procedimiento.\n• EXPERIMENTACIÓN: Los estudiantes ejecutan el experimento en equipos, observan y registran datos.\n• ANÁLISIS Y CONCLUSIONES: Interpretación de resultados, contraste con hipótesis, elaboración de conclusiones.\n• COMUNICACIÓN: Exposición de hallazgos y reflexión sobre el proceso.",
      seqDurante: "• OBSERVACIÓN Y REGISTRO: Los estudiantes observan el fenómeno y registran datos en su cuaderno de campo.\n• MANIPULACIÓN DE VARIABLES: Los estudiantes modifican una variable a la vez y observan los cambios.\n• TRABAJO EN EQUIPOS: Ejecución colaborativa del experimento, distribución de roles.\n• ACOMPAÑAMIENTO DOCENTE: El docente guía, formula preguntas y asegura la correcta ejecución del procedimiento.",
      seqDespues: "• ANÁLISIS DE DATOS: Interpretación de resultados, elaboración de tablas y gráficos simples.\n• CONCLUSIONES: Contraste de hipótesis con resultados, formulación de conclusiones.\n• COMUNICACIÓN: Exposición oral de hallazgos utilizando un póster o presentación.\n• REFLEXIÓN: ¿Qué aprendimos? ¿Cómo podemos aplicar este conocimiento en nuestra vida diaria?",
      seqCierre: "• METACOGNICIÓN: ¿Qué descubrimos? ¿Cómo lo descubrimos? ¿Nuestra hipótesis se cumplió? ¿Por qué?\n• RELACIÓN CON LA VIDA COTIDIANA: ¿Dónde observamos este fenómeno en nuestra vida diaria?\n• COMPROMISO AMBIENTAL: ¿Cómo podemos cuidar nuestro entorno a partir de lo aprendido?\n• RETO: Investigar en casa un fenómeno similar y compartir los hallazgos.",
      gestionAprendizaje: "Define metas de aprendizaje para la indagación científica.\nOrganiza acciones estratégicas: observar, preguntar, experimentar, concluir.\nMonitorea su proceso de indagación y ajusta procedimientos.\nEvalúa la validez de sus conclusiones basadas en evidencias.\nReflexiona sobre su desarrollo del pensamiento científico.",
      resources: "Material de laboratorio (lupas, imanes, termómetros, vasos de precipitado, embudos)\nGuías de experimentos y fichas de registro\nCuaderno de campo\nVideos educativos y documentales\nMaterial reciclable para prototipos\nPlantas, animales pequeños, muestras del entorno\nBalanza, regla, cinta métrica\nLinterna, espejos, lentes",
    },
  },
  secundaria: {
    default: {
      competencies: "Resuelve problemas de cantidad.\nResuelve problemas de regularidad, equivalencia y cambio.\nResuelve problemas de forma, movimiento y localización.\nResuelve problemas de gestión de datos e incertidumbre.\nSe comunica oralmente en su lengua materna.\nLee diversos tipos de textos escritos.\nEscribe diversos tipos de textos.\nConvive y participa democráticamente.\nIndaga mediante métodos científicos.",
      capacities: "Traduce cantidades a expresiones numéricas.\nComunica su comprensión sobre los números y las operaciones.\nUsa estrategias y procedimientos de estimación y cálculo.\nArgumenta afirmaciones sobre relaciones numéricas.\nObtiene información del texto oral y escrito.\nInfiere e interpreta información del texto.\nReflexiona y evalúa la forma, contenido y contexto.\nAdecúa, organiza y desarrolla las ideas de forma coherente.\nProblematiza situaciones para hacer indagación.\nDiseña estrategias para hacer indagación.\nGenera y registra datos e información.\nAnaliza datos e información.",
      performance: "Establece relaciones entre datos y acciones de comparar, igualar, repetir o repartir cantidades en contextos diversos.\nExpresa con representaciones gráficas, tablas y simbología su comprensión de los números racionales.\nEmplea estrategias heurísticas, procedimientos de cálculo y propiedades de las operaciones.\nJustifica sus procesos de resolución y resultados mediante argumentos matemáticos.\nAnaliza críticamente fuentes de información y evalúa su validez.\nEscribe textos argumentativos y expositivos con coherencia, cohesión y adecuación.\nDiseña y ejecuta estrategias de indagación experimental o documental.",
      purpose: "Que los estudiantes desarrollen competencias fundamentales para su formación integral mediante el análisis crítico, la resolución de problemas complejos, la comunicación efectiva y la investigación autónoma, fortaleciendo su capacidad de argumentar, reflexionar y proponer soluciones innovadoras a desafíos de su entorno social, cultural y natural, en el marco de una ciudadanía activa y responsable.",
      evidence: "Resolución de problemas complejos de forma individual y colaborativa con sustento argumentado.\nProducción de textos académicos (ensayos, informes, monografías) con rigor y creatividad.\nSustentación oral de trabajos de indagación e investigación.\nParticipación en debates, mesas redondas y exposiciones argumentadas.\nPortafolio digital o físico que evidencie el proceso de aprendizaje y la reflexión metacognitiva.\nProyectos interdisciplinarios con impacto en la comunidad.",
      transversalApproaches: comunes.enfoques,
      seqInicio: "• DINÁMICA DE ACTIVACIÓN: Actividad rompehielo, situación controversial, pregunta ética, caso problemático o reto cognitivo.\n• EXPLORACIÓN DE SABERES PREVIOS: Estrategia de lluvia de ideas, preguntas exploratorias, organizador previo.\n• CONFLICTO COGNITIVO: Presentación de una situación que evidencie limitaciones en los conocimientos previos.\n• PROPÓSITO Y ORGANIZACIÓN: Comunicación clara del propósito de la sesión y los criterios de evaluación. Organización de equipos de trabajo.\n• ACUERDOS DE CONVIVENCIA: Establecimiento participativo de normas para el trabajo colaborativo.",
      seqDesarrollo: "• PRESENTACIÓN Y ANÁLISIS DE LA INFORMACIÓN: El docente presenta el contenido utilizando diversas fuentes (textos, videos, infografías, datos estadísticos). Análisis guiado mediante preguntas de profundización.\n• TRABAJO COLABORATIVO EN EQUIPOS HETEROGÉNEOS: Los estudiantes abordan situaciones problemáticas o casos aplicando estrategias de pensamiento crítico. Uso de técnicas colaborativas (rompecabezas, estudio de caso, ABP).\n• ACOMPAÑAMIENTO Y RETROALIMENTACIÓN FORMATIVA: El docente monitorea, formula preguntas de andamiaje, identifica dificultades y brinda retroalimentación oportuna y específica.\n• PLENARIA Y SOCIALIZACIÓN: Presentación de resultados, contraste de posturas, debate argumentado. Formalización del conocimiento.\n• APLICACIÓN Y TRANSFERENCIA: Actividad individual donde el estudiante aplica lo aprendido a un nuevo contexto o problema.",
      seqDurante: comunes.seqDuranteDefault,
      seqDespues: comunes.seqDespuesDefault,
      seqCierre: "• METACOGNICIÓN ESTRUCTURADA: ¿Qué aprendí? ¿Cómo lo aprendí? ¿Qué estrategias fueron más efectivas? ¿Qué dificultades enfrenté y cómo las superé? ¿Cómo puedo aplicar esto en mi vida?\n• EVALUACIÓN INTEGRADA: Autoevaluación del logro de los criterios. Coevaluación del trabajo en equipo.\n• RETROALIMENTACIÓN DOCENTE: Síntesis de los aprendizajes clave y reflexión sobre los procesos.\n• ACTIVIDAD DE EXTENSIÓN: Investigación complementaria, lectura sugerida o proyecto personal para profundizar.",
      gestionAprendizaje: comunes.gestion,
      evaluationTechniques: "Observación sistemática del desempeño\nAnálisis de producciones y portafolios\nPruebas escritas de desarrollo\nRúbricas analíticas y holísticas\nGuías de observación de exposiciones y debates\nAutoevaluación y coevaluación estructurada",
      evaluationInstruments: "Rúbrica analítica con niveles de logro\nLista de cotejo de indicadores\nPrueba escrita de desarrollo\nPortafolio de evidencias con reflexiones\nGuía de autoevaluación\nFicha de observación del trabajo en equipo\nEscala de valoración de actitudes",
      resources: "Pizarra acrílica y plumones\nProyector multimedia y laptop\nTextos escolares MINEDU y materiales complementarios\nFichas de trabajo y guías de aprendizaje\nPlataforma educativa virtual (Classroom, Moodle u otra)\nMaterial bibliográfico (libros, revistas, enciclopedias)\nMaterial concreto y de laboratorio según el área\nAcceso a internet para investigación",
      reflections: comunes.reflex,
    },
    "Comunicación": {
      competencies: "Se comunica oralmente en su lengua materna.\nLee diversos tipos de textos escritos en su lengua materna.\nEscribe diversos tipos de textos en su lengua materna.",
      capacities: "Obtiene información del texto oral.\nInfiere e interpreta información del texto oral.\nReflexiona y evalúa la forma, el contenido y contexto del texto oral.\nObtiene información del texto escrito.\nInfiere e interpreta información del texto escrito.\nReflexiona y evalúa la forma, el contenido y contexto del texto escrito.\nAdecúa, organiza y desarrolla las ideas de forma coherente y cohesionada.\nUtiliza convenciones del lenguaje escrito de forma pertinente.\nReflexiona y evalúa la forma, el contenido y contexto de su texto escrito.",
      performance: "Opina críticamente sobre el contenido, la organización textual y las intenciones del autor en textos literarios y no literarios.\nExplica la función de los recursos estilísticos y su efecto en el sentido del texto.\nProduce textos argumentativos (ensayos, artículos de opinión) con una postura clara y argumentos sólidos.\nEvalúa la eficacia de sus textos y los reformula para mejorarlos.\nUtiliza adecuadamente las convenciones gramaticales y ortográficas.\nParticipa en diálogos y debates expresando sus ideas con fundamentos y respetando las opiniones divergentes.",
      purpose: "Que los estudiantes se conviertan en lectores críticos, escritores competentes y comunicadores efectivos, capaces de analizar, interpretar y producir discursos orales y escritos complejos, utilizando estrategias de comprensión y producción que les permitan participar activa y reflexivamente en la vida social, cultural y académica.",
      evidence: "Ensayo argumentativo o artículo de opinión con estructura, tesis y argumentos coherentes.\nAnálisis literario escrito de un texto leído, con identificación de recursos estilísticos y temáticos.\nDebate estructurado con argumentación fundamentada y contrarargumentación.\nPortafolio de producciones escritas con proceso de planificación, textualización y revisión.\nExposición oral con apoyo visual sobre un tema de investigación.",
      seqInicio: "• MOTIVACIÓN: Lectura de un texto breve provocador, frase célebre, imagen polisémica, video documental o noticia de actualidad relacionada con el tema.\n• SABERES PREVIOS: Discusión guiada sobre el tema. ¿Qué sabemos? ¿Qué experiencias tenemos? ¿Qué posturas existen?\n• CONFLICTO COGNITIVO: Presentación de una situación que cuestione las ideas previas o presente una perspectiva novedosa.\n• PROPÓSITO: \"Hoy analizaremos críticamente… y produciremos nuestro propio…\"",
      seqDesarrollo: "• ANÁLISIS DEL DISCURSO ORAL O ESCRITO: Identificación de la situación comunicativa, propósito, estructura, recursos lingüísticos y estilísticos.\n• TRABAJO COLABORATIVO: Aplicación de técnicas de discusión (debate, mesa redonda, panel, foro) o análisis en equipos.\n• PRODUCCIÓN INDIVIDUAL: Planificación, textualización y revisión de textos según el género trabajado.\n• REVISIÓN ENTRE PARES: Coevaluación usando rúbrica, formulación de sugerencias de mejora.\n• REESCRITURA Y MEJORA: Incorporación de sugerencias y publicación o presentación final.",
      seqDurante: "• LECTURA ANALÍTICA: Análisis detallado del texto: estructura, recursos estilísticos, propósito comunicativo.\n• COMPRENSIÓN CRÍTICA: Evaluación de la postura del autor, identificación de sesgos y argumentos.\n• TRABAJO COLABORATIVO: Discusión en grupos sobre interpretaciones y análisis.\n• REGISTRO: Elaboración de fichas de análisis y organizadores gráficos avanzados.",
      seqDespues: "• PRODUCCIÓN TEXTUAL: Planificación, textualización y revisión de un texto académico (ensayo, artículo, reseña).\n• COEVALUACIÓN: Revisión entre pares utilizando rúbrica analítica.\n• REESCRITURA: Mejora del texto a partir de la retroalimentación recibida.\n• PUBLICACIÓN: Presentación final y socialización de las producciones.",
      gestionAprendizaje: "Define metas de aprendizaje para el análisis crítico y la producción textual.\nOrganiza acciones estratégicas: lectura analítica, investigación, planificación de la escritura.\nMonitorea su comprensión y ajusta estrategias de lectura y escritura.\nEvalúa la calidad argumentativa y formal de sus producciones.\nReflexiona sobre su progreso en competencias comunicativas avanzadas.",
      resources: "Textos literarios y no literarios (cuentos, poemas, novelas, artículos, ensayos, crónicas)\nFichas de análisis y comprensión lectora\nRúbrica de producción textual\nDiccionario físico, digital y de sinónimos\nPlataforma educativa virtual\nMedios audiovisuales (videos, documentales, podcast)\nBiblioteca del aula y de la institución",
    },
    "Ciencia y Tecnología": {
      competencies: "Indaga mediante métodos científicos para construir conocimientos.\nExplica el mundo físico basándose en conocimientos sobre los seres vivos, materia y energía, biodiversidad, Tierra y universo.\nDiseña y construye soluciones tecnológicas para resolver problemas de su entorno.",
      capacities: "Problematiza situaciones para hacer indagación.\nDiseña estrategias para hacer indagación.\nGenera y registra datos e información.\nAnaliza datos e información.\nEvalúa y comunica el proceso y resultados de su indagación.\nDetermina una alternativa de solución tecnológica.\nDiseña la alternativa de solución tecnológica.\nImplementa y valida la alternativa de solución tecnológica.\nEvalúa y comunica el funcionamiento y los impactos de su solución tecnológica.",
      performance: "Formula preguntas investigables sobre fenómenos naturales o problemas tecnológicos.\nDiseña procedimientos experimentales o de investigación considerando variables.\nInterpreta datos y establece relaciones causales utilizando gráficos y modelos.\nEvalúa las conclusiones del proceso de indagación y las relaciona con el contexto.\nConstruye prototipos tecnológicos aplicando principios científicos y criterios de funcionamiento.\nArgumenta la importancia de su solución tecnológica y su impacto en la comunidad.",
      purpose: "Que los estudiantes desarrollen una comprensión profunda de los fenómenos naturales y tecnológicos mediante la investigación científica autónoma, aplicando rigurosamente el método científico, utilizando tecnologías de la información y comunicación, y diseñando soluciones innovadoras que respondan a problemáticas reales de su entorno, con responsabilidad ética y ambiental.",
      evidence: "Informe de investigación científica con estructura formal (introducción, marco teórico, metodología, resultados, conclusiones, referencias).\nPrototipo tecnológico funcional con memoria descriptiva del proceso de diseño.\nPresentación multimedia de resultados con sustentación oral.\nArtículo científico breve o póster académico.\nBitácora de laboratorio con registro detallado del proceso de indagación.",
      seqInicio: "• MOTIVACIÓN: Pregunta investigadora, controversia científica, noticia de actualidad sobre ciencia y tecnología, experimento demostrativo o visita al laboratorio.\n• SABERES PREVIOS: ¿Qué sabemos científicamente sobre…? ¿Qué teorías o explicaciones existen?\n• CONFLICTO COGNITIVO: Evidencia empírica que contradice las ideas previas o presenta un problema no resuelto.\n• PROPÓSITO: \"Hoy investigaremos… aplicando el método científico para comprender…\"",
      seqDesarrollo: "• FORMULACIÓN DEL PROBLEMA: Delimitación de la pregunta de investigación.\n• MARCO TEÓRICO: Investigación bibliográfica y revisión de conceptos previos.\n• DISEÑO EXPERIMENTAL O DE INVESTIGACIÓN: Definición de variables, hipótesis, materiales y procedimiento.\n• EJECUCIÓN: Desarrollo del experimento, recolección y registro de datos.\n• ANÁLISIS E INTERPRETACIÓN: Procesamiento de datos, elaboración de gráficos y tablas. Contraste de hipótesis.\n• ELABORACIÓN DE CONCLUSIONES: Respuesta a la pregunta de investigación y reflexión sobre las limitaciones y proyecciones.",
      seqDurante: "• EJECUCIÓN EXPERIMENTAL: Desarrollo riguroso del experimento, control de variables.\n• REGISTRO SISTEMÁTICO: Recolección y registro de datos en tablas y gráficos.\n• TRABAJO EN EQUIPOS: Distribución de roles y responsabilidades en la ejecución.\n• ACOMPAÑAMIENTO DOCENTE: Supervisión, formulación de preguntas de profundización y retroalimentación.",
      seqDespues: "• ANÁLISIS DE DATOS: Procesamiento e interpretación de resultados, uso de herramientas estadísticas.\n• CONTRASTE DE HIPÓTESIS: Confrontación de resultados con las hipótesis formuladas.\n• ELABORACIÓN DE CONCLUSIONES: Síntesis de hallazgos y reflexión sobre limitaciones.\n• COMUNICACIÓN CIENTÍFICA: Elaboración de informe formal y presentación de resultados.\n• PROYECCIÓN: Propuesta de nuevas preguntas de investigación a partir de los hallazgos.",
      gestionAprendizaje: "Define metas de aprendizaje para la investigación científica autónoma.\nOrganiza acciones estratégicas: formular hipótesis, diseñar experimentos, analizar datos.\nMonitorea y ajusta su proceso de indagación según los resultados obtenidos.\nEvalúa críticamente la validez de sus conclusiones basadas en evidencias.\nReflexiona sobre su desarrollo del pensamiento científico y la responsabilidad ética.",
      resources: "Laboratorio equipado con instrumentos básicos\nSensores y dispositivos de medición digital\nSoftware de simulación (PhET, GeoGebra, etc.)\nBibliografía científica (libros, artículos, papers)\nCuaderno de laboratorio\nMaterial de escritorio para prototipos\nEquipo multimedia\nConexión a internet para investigación\nGuías de laboratorio",
    },
  },
}

function detectarAsignatura(title: string, subject: string): string {
  const t = (title + " " + subject).toLowerCase()
  if (t.includes("comunic") || t.includes("lectura") || t.includes("escritur") || t.includes("texto") || t.includes("literatura") || t.includes("cuento") || t.includes("gramática") || t.includes("poesía") || t.includes("poema") || t.includes("ensayo") || t.includes("artículo") || t.includes("debate")) return "Comunicación"
  if (t.includes("matem") || t.includes("númer") || t.includes("problema") || t.includes("geometr") || t.includes("álgebra") || t.includes("estadístic") || t.includes("aritmétic") || t.includes("razonamient")) return "Matemática"
  if (t.includes("ciencia") || t.includes("tecnología") || t.includes("experiment") || t.includes("biolo") || t.includes("físic") || t.includes("químic") || t.includes("indaga") || t.includes("ecosistema") || t.includes("célula")) return "Ciencia y Tecnología"
  if (t.includes("social") || t.includes("histor") || t.includes("geograf") || t.includes("ciudadan") || t.includes("democrac") || t.includes("económ") || t.includes("polític") || t.includes("cultur")) return "Ciencias Sociales"
  if (t.includes("personal") || t.includes("identidad") || t.includes("convivenc") || t.includes("familia") || t.includes("emocion")) return "Personal Social"
  if (t.includes("inglés") || t.includes("english") || t.includes("idioma") || t.includes("foreign")) return "Inglés"
  if (t.includes("arte") || t.includes("artístic") || t.includes("música") || t.includes("danza") || t.includes("teatro") || t.includes("plástic")) return "Arte y Cultura"
  if (t.includes("educación físic") || t.includes("deporte") || t.includes("recreación") || t.includes("salud") || t.includes("gimnasia")) return "Educación Física"
  if (t.includes("religión") || t.includes("religios") || t.includes("formación religiosa") || t.includes("ética") || t.includes("moral")) return "Educación Religiosa"
  return ""
}

export function generarTemplate(level: string, subject: string, title: string): Partial<Template> {
  const nivel = porNivel[level]
  if (!nivel) return {}

  const asignatura = detectarAsignatura(title, subject) || subject

  const template = { ...(nivel.default || {}) }

  if (asignatura && nivel[asignatura]) {
    Object.assign(template, nivel[asignatura])
  }

  if (template.purpose) {
    template.purpose = template.purpose.replace(
      /^Que los estudiantes /,
      `Que los estudiantes de ${level} en el área de ${subject} `
    )
  }

  if (title && template.purpose) {
    const tituloLimpio = title.charAt(0).toLowerCase() + title.slice(1)
    template.purpose = template.purpose + `\n\nA partir de la sesión titulada: "${title}", los estudiantes desarrollarán actividades específicas que les permitirán construir aprendizajes significativos vinculados a su contexto y experiencia.`
  }

  return template
}

export function sugerirRecursos(nivel: string, asignatura: string): string {
  const comunes = "Pizarra, plumones, cuaderno de trabajo, fichas de aplicación, proyector multimedia, laptop, conexión a internet"
  const porAsig: Record<string, string> = {
    "Matemática": `${comunes}\nMaterial concreto (base 10, regletas de Cuisenaire, geoplano, tangram, ábacos)\nCalculadora científica\nSoftware educativo (GeoGebra, Khan Academy)\nTextos escolares MINEDU\nJuegos matemáticos (dominó, bingo numérico, cartas)`,
    "Comunicación": `${comunes}\nTextos literarios y no literarios (cuentos, poemas, artículos, ensayos)\nDiccionario físico y digital\nLáminas, tarjetas léxicas y pictogramas\nBiblioteca del aula\nEquipo de audio y video`,
    "Ciencia y Tecnología": `${comunes}\nMaterial de laboratorio (lupas, termómetros, probetas, imanes)\nModelos didácticos y maquetas\nVideos educativos y simulaciones\nGuías de experimentos\nCuaderno de campo`,
    "Ciencias Sociales": `${comunes}\nMapas físicos y políticos\nFuentes históricas (documentos, imágenes, testimonios)\nAtlas geográfico\nVideos documentales\nLíneas de tiempo y organizadores visuales`,
    "Personal Social": `${comunes}\nLáminas ilustrativas\nMaterial reciclable\nJuegos de roles\nCuentos y fábulas\nEspejo y materiales de autoconocimiento`,
    "Inglés": `${comunes}\nFlashcards y posters\nCanciones y videos en inglés\nJuegos de vocabulario\nAplicaciones interactivas\nTextos graduados`,
    "Arte y Cultura": `${comunes}\nMateriales de dibujo y pintura\nInstrumentos musicales\nDisfraces y utilería\nReproductor de audio\nObras de arte impresas o digitales`,
    "Educación Física": `${comunes}\nBalones, conos, cuerdas, aros\nCronómetro y silbato\nColchonetas y material de psicomotricidad\nEquipo de sonido`,
    "Educación Religiosa": `${comunes}\nBiblia y textos sagrados\nImágenes religiosas\nCanciones y alabanzas\nMaterial de reflexión`,
  }
  return porAsig[asignatura] || `${comunes}\nMaterial didáctico diverso según la actividad planificada`
}

export function sugerirEvaluacion(nivel: string, asignatura: string): { techniques: string; instruments: string } {
  const baseTec = "Observación sistemática\nAnálisis de producciones y trabajos\nPruebas escritas y orales\nPrácticas dirigidas\nAutoevaluación y coevaluación"
  const baseInst = "Lista de cotejo\nRúbrica analítica\nFicha de observación\nPrueba escrita\nPortafolio de evidencias\nEscala de valoración"
  return { techniques: baseTec, instruments: baseInst }
}
